#
# This source file is part of the MyHeartCounts based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: MyHeartCounts.xcodeproj
schemes:
- MyHeartCounts
targets:
- MyHeartCounts
- MyHeartCountsTests
- MyHeartCountsUITests
